pythoncampusiff_inscricao/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('pythoncampusiff_inscricao.views',
    (r'^$', 'inscricao'),
    (r'^confirmar$', 'confirmar_inscricao'),
    (r'^buscar_inscrito$','buscar_inscrito'),
    (
        r'^lista_de_presenca_do_minicurso/(?P<minicurso_id>\d+)$',
        'lista_de_presenca_do_minicurso'
    ),
    (r'^listas_de_presenca$','listas_de_presenca'),
    (r'^lista_de_presenca_das_palestras$','lista_de_presenca_das_palestras'),
    (r'^organizacao$','organizacao'),
    (r'^inscricao_login','inscricao_login'),
    (r'^inscricao_logout','inscricao_logout'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('pythoncampusiff_base.urls')),
    (r'^programacao/', include('pythoncampusiff_programacao.urls')),
    (r'^inscricao/', include('pythoncampusiff_inscricao.urls')),
    (r'^contato/', include('pythoncampusiff_contato.urls')),
    (r'^atividades/', include('pythoncampusiff_atividades.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^site_media/(.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}
    ),
)

pythoncampusiff_inscricao/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.mail import send_mail
from pythoncampusiff_atividades.models import Atividade

class Inscrito(models.Model):
    ESTADOS = (('pendente', 'Pendente'),
              ('confirmado', 'Confirmado'),
              ('espera', 'Espera'))
    
    nome = models.CharField(verbose_name='nome',max_length=100)
    instituicao = models.CharField(verbose_name='instituição',max_length=100)
    cpf = models.CharField(verbose_name='CPF',max_length=11,unique=True)
    email = models.EmailField(verbose_name='E-mail')
    minicurso_da_manha = models.ForeignKey(
        Atividade,
        null=True,
        blank=True,
        related_name='minicurso_da_manha',
        verbose_name='minicurso da manhã'
    )
    minicurso_da_tarde = models.ForeignKey(
        Atividade,
        null=True,
        blank=True,
        related_name='minicurso_da_tarde',
        verbose_name='minicurso da tarde'
    )
    estado = models.CharField(
        max_length=20,
        choices=ESTADOS,
        default='pendente'
    )
    
    def __unicode__(self):
        return self.nome

    def inscrever(self, minicurso_id, periodo):
        minicurso = Atividade.objects.get(id=minicurso_id)
        if periodo == 'manha':
            self.minicurso_da_manha = minicurso
        elif periodo == 'tarde':
            self.minicurso_da_tarde = minicurso
        # Adicionar id de inscricao no e-mail
        #send_mail(u'[PythOnCampus IFF] Confirme sua presença!', u'Atenção! Para assegurar sua vaga nos minicursos, traga 1kg de arroz, feijão ou macarrão para cada minicurso no qual você estiver inscrito até 10/11/2009. O local de confirmação e arrecadação é o NSI - Núcleo de Pesquisa em Sistemas de Informação (Sala 104, Bloco F), localizado no IFF Campus Campos-Centro (Antigo Cefet Campos), das 14:00 às 19:00 hs. Importante: Será respeitada a ordem de entrega do alimento para o preenchimento das vagas!', 'pythoncampus@iff.edu.br', [self.email,], fail_silently=True)

    def confirmar_inscricao(self):
        try:
            self.minicurso_da_manha.decrementar_vaga()
        except AttributeError:
            pass

        try:
            self.minicurso_da_tarde.decrementar_vaga()
        except AttributeError:
            pass

    def save(self,*args,**kwargs):
        super(Inscrito, self).save(*args,**kwargs)
        if self.estado == 'confirmado':
            self.confirmar_inscricao()

pythoncampusiff_inscricao/forms.py
from django import forms
from django.contrib.localflavor.br.forms import BRCPFField
from models import Inscrito

class FormularioDeInscrito(forms.ModelForm):
    cpf = BRCPFField(label='CPF')

    class Meta:
        model = Inscrito
        exclude = ('estado','minicurso_da_manha','minicurso_da_tarde')

pythoncampusiff_inscricao/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout
from django.contrib.auth import authenticate, login
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import simplejson
from pythoncampusiff_atividades.models import Atividade
from forms import FormularioDeInscrito
from models import Inscrito


def inscricao(request):
    formulario = FormularioDeInscrito()
    if request.method == 'POST':
        formulario = FormularioDeInscrito(request.POST)
        if formulario.is_valid():
            inscrito = formulario.save(commit=False)
            inscrito_em_minicurso = False
            minicurso_da_manha = request.POST.get('minicurso_da_manha','')
            minicurso_da_tarde = request.POST.get('minicurso_da_tarde','')
            if minicurso_da_manha != '':
                inscrito.inscrever(minicurso_da_manha,'manha')
                inscrito_em_minicurso = True
            if minicurso_da_tarde != '':
                inscrito.inscrever(minicurso_da_tarde,'tarde')
                inscrito_em_minicurso = True
            inscrito.save()
            return render_to_response(
                'sucesso_na_inscricao.html',
                {
                    'inscrito':inscrito,
                    'inscrito_em_minicurso': inscrito_em_minicurso
                },
                context_instance = RequestContext(request)
            )
    return render_to_response(
        'inscricao.html',
        {'formulario': formulario},
        context_instance = RequestContext(request)
    )
@login_required
def confirmar_inscricao(request):
    minicursos = Atividade.objects.filter(tipo='Minicurso')
    if request.method == 'POST':
        id_inscrito = request.POST.get('id_inscrito')
        inscrito = Inscrito.objects.get(id=id_inscrito)
        inscrito.estado = 'confirmado'
        inscrito.save()
        return render_to_response(
            'confirmar_inscricao.html',
            {
                'minicursos': minicursos,
                'mensagem': u'Confirmação Realizada Com Sucesso!'
            },
            context_instance = RequestContext(request)
        )
    return render_to_response(
        'confirmar_inscricao.html',
        {'minicursos': minicursos},
        context_instance = RequestContext(request)
    )

def buscar_inscrito(request):
    identificacao = request.GET.get('identificacao')
    try:
        identificacao_int = int(identificacao)
        try:
            inscrito = Inscrito.objects.get(id=identificacao_int)
        except Inscrito.DoesNotExist:
            inscrito = None
    except ValueError:
        try:
            inscrito = Inscrito.objects.get(nome=identificacao.upper())
        except Inscrito.DoesNotExist:
            inscrito = None
    
    if inscrito is not None:
        minicurso_da_manha = inscrito.minicurso_da_manha
        minicurso_da_tarde = inscrito.minicurso_da_tarde
        
        status_minicurso_da_manha = ''
        status_minicurso_da_tarde = ''
        
        if minicurso_da_manha is not None:
            minicurso_da_manha_titulo = minicurso_da_manha.titulo
            if minicurso_da_manha.vagas_disponiveis > 0:
                status_minicurso_da_manha = u'Disponível'
            else:
                status_minicurso_da_manha = 'Esgotado'
        else:
            minicurso_da_manha_titulo = 'Nenhum'
            status_no_minicurso_da_manha = ''
        
        if minicurso_da_tarde is not None:
            minicurso_da_tarde_titulo = minicurso_da_tarde.titulo
            if minicurso_da_tarde.vagas_disponiveis > 0:
                status_minicurso_da_tarde = u'Disponível'
            else:
                status_minicurso_da_tarde = 'Esgotado'
        else:
            minicurso_da_tarde_titulo = 'Nenhum'
            status_no_minicurso_da_tarde = ''
        
        resposta = simplejson.dumps(
            [{
                'inscritoEncontrado': 'True',
                'idInscrito': inscrito.id,
                'nomeInscrito': inscrito.nome,
                'estadoInscrito': inscrito.estado,
                'minicurso_da_manha': minicurso_da_manha_titulo,
                'minicurso_da_tarde': minicurso_da_tarde_titulo,
                'status_minicurso_da_manha': status_minicurso_da_manha,
                'status_minicurso_da_tarde': status_minicurso_da_tarde,
            }],
            ensure_ascii = False
        )
    else:
        resposta = simplejson.dumps(
            [{
                'inscritoEncontrado': 'False',
                'identificacao': identificacao,
            }]
        )

    return HttpResponse(resposta, mimetype = "aplication/json")

@login_required
def lista_de_presenca_do_minicurso(request, minicurso_id):
    minicurso = Atividade.objects.get(id=minicurso_id)
    if minicurso.hora.isoformat()[:5] < '12:00':
        inscritos =\
    minicurso.minicurso_da_manha.filter(estado='confirmado').order_by('nome')
    elif minicurso.hora.isoformat()[:5] > '12:00':
        inscritos =\
    minicurso.minicurso_da_tarde.filter(estado='confirmado').order_by('nome')
    
    return render_to_response(
        'lista_de_presenca_do_minicurso.html',
        {
            'minicurso': minicurso,
            'inscritos': inscritos
        },
        context_instance = RequestContext(request)
    )

@login_required
def lista_de_presenca_das_palestras(request):
    inscritos = Inscrito.objects.all().order_by('nome')
    return render_to_response(
        'lista_de_presenca_das_palestras.html',
        {'inscritos': inscritos},
        context_instance = RequestContext(request)
    )

@login_required
def listas_de_presenca(request):
    minicursos = Atividade.objects.filter(tipo='Minicurso')
    return render_to_response(
        'listas_de_presenca.html',
        {'minicursos': minicursos},
        context_instance = RequestContext(request)
    )

def organizacao(request):
    return render_to_response(
        'organizacao.html',
        context_instance = RequestContext(request)
    )
#Login e Logout
def inscricao_login(request):
    nome_de_usuario = request.POST['nome_de_usuario']
    senha = request.POST['senha']
    usuario = authenticate(username=nome_de_usuario, password=senha)
    if usuario is not None:
        if usuario.is_active:
            login(request, usuario)
            return HttpResponseRedirect('/inscricao/organizacao')
        else:
            return render_to_response(
                'organizacao.html',
                {'mensagem_de_erro':u'Sua conta está inativa!'},
                context_instance = RequestContext(request)
            )
    else:
        return render_to_response(
            'organizacao.html',
            {'mensagem_de_erro':u'Login ou Senha inválido!'},
            context_instance = RequestContext(request)
        )

def inscricao_logout(request):
    logout(request)
    return HttpResponseRedirect('/inscricao/organizacao')

pythoncampusiff_inscricao/templates/confirmar_inscricao.html
{% extends "organizacao.html" %}

{% block titulo %} - Confirmar Inscrição{% endblock titulo %}

{% block estilo_extra %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/estilo/pythoncampusiff_inscricao/confirmar.css" />
{% endblock estilo_extra %}

{% block scripts %}
    <script type="text/javascript" src="{{ MEDIA_URL }}/javascripts/jquery-1.4.2.js"></script>
    <script type="text/javascript">
        function limpar(){
            $('#formulario_confirmacao').hide();
            $('#id_inscrito').attr('value','');
            $('#dados_do_inscrito').html('');
            $('#mensagem').html('');
            $('#identificacao').focus();
        }
        $(document).ready(function(){
            $('#formulario_confirmacao').hide();
            $('#identificacao').focus();
            $('#botao_buscar').click(function(){
                limpar();
                $.get(
                    '/inscricao/buscar_inscrito',
                    {'identificacao':$('#identificacao').val()},
                    function(resposta) {
                        if(resposta[0].inscritoEncontrado == 'True') {
                            html = '<h2>Dados do Inscrito</h2>';
                            html += '<div>Nome do inscrito: '+resposta[0].nomeInscrito+'</div>';
                            if(resposta[0].estadoInscrito == 'confirmado') {
                                html += '<div>Estado do inscrito: <span class="atencao">'+resposta[0].estadoInscrito+'</span></div>';
                            }
                            else {
                                html += '<div>Estado do inscrito: <span class="disponivel">'+resposta[0].estadoInscrito+'</span></div>';
                            }
                            
                            html += '<div>Minicurso da manhã: '
                            if(resposta[0].minicurso_da_manha != 'Nenhum') {
                                html += resposta[0].minicurso_da_manha;
                            }
                            else {
                                html += '<span class="atencao">'+resposta[0].minicurso_da_manha+'</span>';
                            }
                            
                            if(resposta[0].estadoInscrito != 'confirmado') {
                                if(resposta[0].status_minicurso_da_manha == 'Disponível') {
                                    html += ' - <span class="disponivel"> '+resposta[0].status_minicurso_da_manha+'</span></div>';
                                }
                                else {
                                    html += ' - <span class="esgotado"> '+resposta[0].status_minicurso_da_manha+'</span></div>';
                                }
                            }
                            
                            html += '<div>Minicurso da tarde: ';                            
                            if(resposta[0].minicurso_da_tarde != 'Nenhum') {
                                html += resposta[0].minicurso_da_tarde;
                            }
                            else {
                                html += '<span class="atencao">'+resposta[0].minicurso_da_tarde+'</span>';
                            }
                            
                            if(resposta[0].estadoInscrito != 'confirmado') {
                                if(resposta[0].status_minicurso_da_tarde == 'Disponível') {
                                    html += ' - <span class="disponivel"> '+resposta[0].status_minicurso_da_tarde+'</span></div>';   
                                }
                                else {
                                    html += ' - <span class="esgotado"> '+resposta[0].status_minicurso_da_tarde+'</span></div>';
                                }
                            }
                            
                            $('#mensagem').html('');
                            $('#dados_do_inscrito').html(html);
                            $('#id_inscrito').attr('value',resposta[0].idInscrito);
                            if((resposta[0].estadoInscrito != 'confirmado') &&
                              ((resposta[0].minicurso_da_manha != 'Nenhum') || (resposta[0].minicurso_da_tarde != 'Nenhum')) &&
                              ((resposta[0].status_minicurso_da_manha == 'Disponível') || (resposta[0].status_minicurso_da_tarde == 'Disponível'))
                              )
                            {
                                $('#formulario_confirmacao').show();
                            }
                        }
                        else {
                            $('#mensagem').html('Nenhum resultado encontrado para '+resposta[0].identificacao);
                        }
                    }
                );
            });
            $('#botao_limpar').click(function(){
                $('#identificacao').attr('value','');
                limpar();
            });
        });
    </script>
{% endblock scripts %}

{% block subconteudo %}
    <h1>Confirmar Inscrição</h1>
    <div id="minicursos">
        <table>
            <th>
                Minicurso
            </th>
            <th>
                Vagas Disponíveis
            </th>
            <th>
                Horário
            </th>
            {% for minicurso in minicursos %}
                <tr>
                    <td><a href="/inscricao/lista_de_presenca_do_minicurso/{{ minicurso.id }}">{{ minicurso.titulo }}</a></td>
                    <td class="vagas">
                        {% ifnotequal minicurso.vagas_disponiveis 0 %}
                            {{ minicurso.vagas_disponiveis }}
                        {% else %}
                            <span class="atencao">{{ minicurso.vagas_disponiveis }}</span>
                        {% endifnotequal %}
                    </td>
                    <td class="vagas">{{ minicurso.hora }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div id="confirmacao">
        <span>Informe o código do inscrito ou o nome completo usado para inscrição: </span>
        <input type="text" id="identificacao" />
        <input type="button" id="botao_buscar" value=" Buscar " />
        <input type="button" id="botao_limpar" value=" Limpar " />
        <div id="mensagem">{{ mensagem }}</div>
        <div id="dados_do_inscrito"></div>
        <div id="formulario_confirmacao">
            <form method="post" action="">{% csrf_token %}
                <input type="hidden" value="" id="id_inscrito" name="id_inscrito" />
                <input type="submit" value=" Confirmar " />
            </form>
        </div>
    </div>
{% endblock subconteudo %}

pythoncampusiff_inscricao/templates/inscricao.html
{% extends "pagina_base.html" %}

{% block titulo %} - Inscrição{% endblock titulo %}

{% block estilo_extra %}
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/estilo/pythoncampusiff_inscricao/inscricao.css" />
{% endblock estilo_extra %}

{% block scripts %}
    <script type="text/javascript" src="{{ MEDIA_URL }}/javascripts/jquery-1.4.2.js"></script>
    <script type="text/javascript">
        function esconder_minicursos()
            {
                $('#minicursos').hide();
                $('#minicursos_da_manha').html('');
                $('#minicursos_da_tarde').html('');
                $('#aviso_minicurso').show();
                $('#botao_exibir_minicursos').show();
            }

        function exibir_minicursos()
            {
                $.post(
                    '/atividades/minicursos_da_manha',
                    {},
                    function(data) {
                        $('#minicursos_da_manha').html(data);
                    }
                );
                $.post(
                    '/atividades/minicursos_da_tarde',
                    {},
                    function(data) {
                        $('#minicursos_da_tarde').html(data);
                    }
                );
                $('#minicursos').show();
                $('#botao_exibir_minicursos').hide();
                $('#botao_minicursos_hide').show();
                $('#aviso_minicurso').hide();
            }

        function mascara_maiusculo() {
            $('#id_nome').keyup(function(){
                $(this).attr('value',$(this).val().toUpperCase());
            });
            $('#id_instituicao').keyup(function(){
                $(this).attr('value',$(this).val().toUpperCase());
            });
        }

        function mascara_cpf() {
            $('#id_cpf').keyup(function(){
                if ($(this).val().length <= 11) {
                    $(this).attr(
                        'value',
                        $(this).val()
                            .replace(/\D/g,'')
                    );
                }
                else {
                    $(this).attr('value',$(this).val().substr(0,11));
                }
            });
        }

        $(document).ready(function(){
            mascara_cpf();
            mascara_maiusculo();
            esconder_minicursos();
            $('#exibir_minicursos').click(function(){
                exibir_minicursos();
            });
            $('#esconder_minicursos').click(function(){
                esconder_minicursos();
            });
            $('#id_nome').focus();
        });
    </script>
{% endblock scripts %}

{% block conteudo %}
    <h1>Inscrições</h1>
    <!--<p>-->
    <!--    As inscrições estarão disponíveis a partir do dia 03 de novembro de 2010. Aguarde!-->
    <!--</p>-->
    <form method="post" action="">{% csrf_token %}
        {% for field in formulario %}
            <div class="field">
                <div>{{ field.label_tag }}:</div>
                <div>{{ field }}</div>
                <div>{{ field.help_text }}</div>
                <div>{{ field.errors }}</div>
            </div>
        {% endfor %}
        <div class="aviso_minicurso" id="aviso_minicurso">
            Para participar apenas das palestras, clique em " Confirmar inscrição ".
        </div>
        <div id="minicursos">
            <div id="minicursos_da_manha"></div>
            <div id="minicursos_da_tarde"></div>
            <div class="aviso">
                Para assegurar sua vaga, traga 1kg de arroz, feijão ou macarrão para cada minicurso no qual você estiver inscrito até 26/11/2009.<br/>
                Será respeitada a ordem de entrega dos alimentos.
             </div>
            <div id="botao_minicursos_hide" style="display: none;">
                <input type="button" id="esconder_minicursos" value="Não desejo mais participar dos minicursos.">
            </div>
        </div>
        <div id="botao_exibir_minicursos">
            <input type="button" id="exibir_minicursos" value="Desejo participar dos minicursos.">
         </div>
        <input type="submit" value=" Confirmar inscrição " />
    </form>
{% endblock conteudo %}

pythoncampusiff_inscricao/templates/lista_de_presenca_das_palestras.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
<head>
    <title>Lista de Presença das Palestras</title>
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/estilo/pythoncampusiff_inscricao/lista_de_presenca.css"/>
</head>
<body>
    <div id="cabecalho">
        <div id="logo">
            <img alt="PythOnCampus IFF" title="PythOnCampus IFF" src="{{ MEDIA_URL }}/imagens/pythoncampusiff_base/logo.png"/>
        </div>
    </div>
    <h1>Lista de Presença das Palestras</h1>
    <table>
        <th>
            Nome
        </th>
        <th>
            Assinatura
        </th>
        {% for inscrito in inscritos %}
            <tr>
                <td>{{ inscrito.nome }}</td>
                <td></td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

pythoncampusiff_inscricao/templates/lista_de_presenca_do_minicurso.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
<head>
    <title>Lista de Presença do Minicurso "{{ minicurso.titulo }}"</title>
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/estilo/pythoncampusiff_inscricao/lista_de_presenca.css"/>
</head>
<body>
    <div id="cabecalho">
        <div id="logo">
            <img alt="PythOnCampus IFF" title="PythOnCampus IFF" src="{{ MEDIA_URL }}/imagens/pythoncampusiff_base/logo.png"/>
        </div>
        <div id="dados_do_minicurso">
            <div>Minicurso: {{ minicurso.titulo }}</div>
            <div>Responsável: {{ minicurso.responsavel.nome }}</div>
            <div>Início: {{ minicurso.hora }}</div>
        </div>
    </div>
    <h1>Lista de Presença</h1>
    <table>
        <th>
            Nome
        </th>
        <th>
            Assinatura
        </th>
        {% for inscrito in inscritos %}
            <tr>
                <td>{{ inscrito.nome }}</td>
                <td></td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>

pythoncampusiff_inscricao/templates/listas_de_presenca.html
{% extends "organizacao.html" %}

{% block titulo %} - Listas de Presença{% endblock titulo %}

{% block subconteudo %}
    <h1>Listas de Presença</h1>
    <h2>Minicursos</h2>
    <ul>
        {% for minicurso in minicursos %}
            <li><a href="/inscricao/lista_de_presenca_do_minicurso/{{ minicurso.id }}">{{ minicurso.titulo }}</a></li>
        {% endfor %}
    </ul>
    <h2>Outros</h2>
    <ul>
        <li><a href="/inscricao/lista_de_presenca_das_palestras">Palestras</a></li>
    </ul>
{% endblock subconteudo %}

pythoncampusiff_inscricao/templates/organizacao.html
{% extends "pagina_base.html" %}

{% block titulo %} - Organização{% endblock titulo %}

{% block estilo_extra %}
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/estilo/pythoncampusiff_inscricao/organizacao.css" />
{% endblock estilo_extra %}

{% block scripts %}
    <script type="text/javascript" src="{{ MEDIA_URL }}/javascripts/jquery-1.4.2.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
           $('#nome_de_usuario').focus(); 
        });
    </script>
{% endblock scripts %}

{% block conteudo %}
    {% if user.is_authenticated %}
    <div id="topnav" class="topnav">
        <div id="mensagem_usuario">
            Bem Vindo,
            {% ifnotequal user.first_name ''%}
                {{ user.first_name }} |
            {% else %}
                {{ user.username }} |
            {% endifnotequal %}
        </div>
        <div id="signoff_div">
            <form method="post" id="signoff" action="/inscricao/inscricao_logout">{% csrf_token %}
                <input id="signoff_submit" value="Sair" tabindex="6" type="submit">
            </form>
        </div>
    </div>
    <div class="submenu_titulo">Submenu da organização</div>
    <div class="submenu">
        <ul id="navegacao_organizacao">
            <li><a href="/inscricao/confirmar">Confirmar inscrição</a></li>
            <li><a href="/inscricao/listas_de_presenca">Listas de presenca</a></li>
        </ul>
    </div>
    {% block subconteudo %}
        
    {% endblock subconteudo %}
    {% else %}
        <h1>Área Restrita</h1>
        <div id="container_login">
            <form method="post" id="signin" action="/inscricao/inscricao_login">{% csrf_token %}
                <div>
                    <label for="nome_de_usuario">Nome de usuário:</label>
                </div>
                <div>
                    <input  type="text" id="nome_de_usuario" name="nome_de_usuario" title="nome de usuario" />
                </div>
                <div>
                    <label for="senha">Senha:</label>
                </div>
                <div>
                    <input type="password" id="senha" name="senha" title="senha" />
                </div>
                <div>
                    <input type="submit" id="signin_submit" value="Entrar" />
                </div>
            </form>
            <div>
                <span id="mensagem_de_erro">
                    {% if mensagem_de_erro %}
                        {{ mensagem_de_erro }}
                    {% endif %}
                </span>
            </div>
        </div>
    {% endif %}
{% endblock conteudo %}

pythoncampusiff_inscricao/templates/sucesso_na_inscricao.html
{% extends "pagina_base.html" %}

{% block titulo %} - Inscrição Realizada com Sucesso{% endblock titulo %}

{% block estilo_extra %}
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/estilo/pythoncampusiff_inscricao/inscricao.css" />
{% endblock estilo_extra %}

{% block conteudo %}
    <h1>Inscrição realizada com sucesso</h1>
    <p>
        <strong>{{ inscrito.nome }}</strong>, seu código de inscrição é <strong>{{ inscrito.id }}</strong>.
    </p>
    {% if inscrito_em_minicurso %}
        <p>
            <span class="aviso">Não se esqueça de levar o alimento até o NSI para confirmar a sua inscrição
            no(s) minicurso(s).<br />
            Você receberá um e-mail com maiores instruções a respeito da entrega do alimento.
            </span>
        </p>
    {% endif %}
    <p>
        <strong>A organização da PythOnCampus IFF agradece o seu interesse!</strong>
    </p>
{% endblock conteudo %}